[project]
name = "password-strength-checker"
version = "0.1.0"
description = "A simple password strength checker"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest>=8.4.2",
]

[dependency-groups]
dev = [
    "black>=25.9.0",
]
